spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/news_release
    username: news
    password: s21014
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    property-naming-strategy: SNAKE_CASE